version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: backend/server:latest
    ports:
      - "8081:8081"

  database:
    image: postgres:17.6
    environment:
      - POSTGRES_PASSWORD=devpass
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

